import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { Button } from '../components/Button';
import { LeadForm } from '../components/LeadForm';
export const Route = createFileRoute('/demo')({ component: Demo, head: () => ({ meta: [{ title: 'Try the demo — API Mender' }] }) });
const stages = ['The project', 'The change', 'The impact', 'The proposed fix', 'The review'];
const before = `return stripe.paymentIntents.create({\n  amount,\n  currency: "usd",\n});`;
const after = `return stripe.paymentIntents.create({\n  amount,\n  currency: "usd",\n  capture_method: "automatic",\n});`;
const patch = `--- a/src/payments.ts\n+++ b/src/payments.ts\n@@ -9,4 +9,5 @@\n   return stripe.paymentIntents.create({\n     amount,\n     currency: "usd",\n+    capture_method: "automatic",\n   });\n`;
function Demo() {
  const [step, setStep] = useState(0);
  const [intent, setIntent] = useState<'early'|'partner'>('early');
  function download() { const url = URL.createObjectURL(new Blob([patch], {type:'text/plain'})); const a = document.createElement('a'); a.href=url; a.download='sample-fix.patch'; a.click(); setTimeout(()=>URL.revokeObjectURL(url),1000); }
  return <main className="min-h-screen bg-background text-foreground">
    <header className="page-shell flex min-h-18 flex-wrap items-center justify-between gap-4 py-4"><a href="/" className="font-mono text-sm"><span className="text-primary">API</span> Mender</a><a href="#demo-contact" className="text-sm font-semibold">Get early access →</a></header>
    <section className="section-rule technical-grid py-12 sm:py-16"><div className="page-shell"><p className="font-mono text-xs uppercase text-primary">Interactive walkthrough · No login needed</p><h1 className="mt-4 max-w-3xl text-4xl font-semibold sm:text-5xl">One API change.<br/>From surprise to a proposed fix.</h1><p className="mt-5 max-w-2xl leading-7 text-muted-foreground">Follow a checkout team through a sample Stripe change. Inspect the evidence, the affected code, and the repair before a human reviews it.</p><p className="mt-6 max-w-3xl rounded-md border border-border bg-card p-4 text-sm leading-6"><strong>Simulated case.</strong> Stripe has not announced this required-field change. This walkthrough uses the team’s reproducible fixture; it does not scan your repository, run live checks, or open a GitHub PR.</p></div></section>
    <section className="page-shell py-10 sm:py-14" aria-label="Demo walkthrough"><nav className="mb-8 grid grid-cols-2 gap-2 sm:grid-cols-5" aria-label="Demo steps">{stages.map((label,i)=><button key={label} aria-current={step===i?'step':undefined} onClick={()=>setStep(i)} className={`rounded-md border p-3 text-left text-sm ${step===i?'border-primary bg-accent':'border-border bg-card'}`}><span className="mr-2 font-mono text-primary">0{i+1}</span>{label}</button>)}</nav>
      <div className="grid gap-6 lg:grid-cols-[1.5fr_1fr]">
        <article className="min-w-0 rounded-lg border border-border bg-card p-6 sm:p-9" aria-live="polite">
          <p className="font-mono text-xs text-primary">STEP {step+1} / 5</p>
          <h2 className="mt-4 text-2xl font-semibold">{['Meet the sample checkout project','A new request field becomes required','The checkout call omits the new field','A small change, ready to inspect','Review the evidence before shipping'][step]}</h2>
          <p className="mt-4 leading-7 text-muted-foreground">{[
            'The sample acme/checkout project creates payments using Stripe. The fixture identifies one static call in src/payments.ts. Its live API version is unresolved.',
            'In this invented contract update, POST /v1/payment_intents requires capture_method. Comparing the two sample contracts reveals the new requirement.',
            'The recognized payment call supplies amount and currency, but no capture_method. Under the sample contract, that request would fail the required-field check.',
            'The fixture adds capture_method: "automatic" to preserve the assumed immediate-capture behavior. A developer still needs to confirm that assumption.',
            'The reproducible fixture includes a regression test that fails before the fix and passes afterward. These are recorded fixture results, not checks running in this browser.'
          ][step]}</p>
          {step===1 ? <div className="mt-6 grid gap-4 sm:grid-cols-2"><Code title="Previous sample contract" text={'required: ["amount", "currency"]'}/><Code title="Updated sample contract" text={'required: ["amount", "currency",\n  "capture_method"]'}/></div> : step===3 ? <div className="mt-6 space-y-4"><Code title="Before" text={before}/><Code title="Proposed change" text={after}/></div> : step===4 ? <div className="mt-6 space-y-3">{['TypeScript syntax','Required-field regression','Existing payment test'].map(name=><div key={name} className="flex justify-between gap-3 rounded-md bg-success-muted p-4 text-sm"><span>{name}</span><strong className="text-success">Passed in fixture</strong></div>)}<Button variant="secondary" onClick={download}>Download sample patch ↓</Button><p className="text-xs leading-5 text-muted-foreground">No PR has been published. Downloading does not change any repository.</p></div> : <div className="mt-6"><Code title="src/payments.ts · payment creation" text={before}/></div>}
          <div className="mt-8 flex flex-wrap justify-between gap-3"><Button variant="secondary" disabled={step===0} onClick={()=>setStep(step-1)}>← Back</Button>{step<4?<Button onClick={()=>setStep(step+1)}>{['See the API change','Find the affected code','Inspect the proposed fix','Review validation'][step]} →</Button>:<Button variant="secondary" onClick={()=>setStep(0)}>Start again</Button>}</div>
        </article>
        <aside className="space-y-5"><div className="rounded-lg border border-border bg-card p-6"><p className="font-mono text-xs text-muted-foreground">CASE FILE</p><h3 className="mt-4 font-semibold">acme / checkout</h3><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-muted-foreground">Provider</dt><dd>Stripe · sample integration</dd></div><div><dt className="text-muted-foreground">Affected call</dt><dd className="break-all font-mono text-xs">stripe.paymentIntents.create</dd></div><div><dt className="text-muted-foreground">Status</dt><dd>{step===4?'Ready for human review':'Exploring sample evidence'}</dd></div></dl></div><div className="rounded-lg border border-primary/30 bg-accent p-6"><h3 className="font-semibold">What works today?</h3><p className="mt-3 text-sm leading-6">The separate prototype scans recognized Stripe calls in public repositories and checks official source updates. General impact analysis and automatic repair are still in development.</p><a href="https://github.com/arkaraae/api-mender" target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm underline">View the team’s prototype ↗</a></div></aside>
      </div>
    </section>
    <section id="demo-contact" className="section-rule bg-secondary py-16"><div className="page-shell grid gap-10 lg:grid-cols-2"><div><p className="font-mono text-xs text-primary">FROM THE SAMPLE TO YOUR TEAM</p><h2 className="mt-4 text-3xl font-semibold">Want this for your own repository?</h2><p className="mt-5 max-w-md leading-7 text-muted-foreground">Tell us you’re interested. We’re looking for teams who want better visibility into API changes—and a say in what we build next.</p></div><div className="rounded-lg border border-border bg-card p-6 sm:p-8"><LeadForm intent={intent} onIntentChange={setIntent} source="demo"/></div></div></section>
    <footer className="page-shell py-8 text-sm text-muted-foreground"><a href="/">← Back to API Mender</a></footer>
  </main>;
}
function Code({title,text}:{title:string;text:string}) { return <div className="min-w-0 overflow-hidden rounded-md bg-code"><p className="border-b border-white/10 px-4 py-3 font-mono text-xs text-primary">{title}</p><pre className="overflow-x-auto p-4 text-xs leading-7 text-white/90"><code>{text}</code></pre></div>; }
