import { BrandMark } from './brand-logo';
const cards = [
  { column: 'Detected', count: '02', tint: 'lavender', items: [{ icon: 'S', provider: 'Stripe', title: 'Node SDK release', detail: 'New version available', badge: 'Source update', badgeTone: 'violet', foot: 'Official release · just now' }, { icon: 'S', provider: 'Stripe', title: 'OpenAPI snapshot', detail: 'Specification changed', badge: 'Needs comparison', badgeTone: 'blue', foot: 'OpenAPI · 2 hours ago' }] },
  { column: 'Needs review', count: '01', tint: 'peach', items: [{ icon: '↗', provider: 'Payments service', title: 'PaymentIntent.create', detail: 'Recognized call site', badge: 'Review evidence', badgeTone: 'orange', foot: 'src/payments/charge.ts:48' }] },
  { column: 'Ready to patch', count: '01', tint: 'mint', items: [{ icon: '✓', provider: 'Checkout API', title: 'Update prepared', detail: 'Validation completed', badge: 'Human approval', badgeTone: 'green', foot: 'Preview workflow' }] },
];

export default function ProductPreview() {
  return <div className="product-preview" aria-label="Illustrative API Mender change board">
    <aside className="preview-sidebar"><div className="preview-workspace"><span className="preview-workspace-avatar">A</span><strong>Acme engineering</strong><span className="preview-chevron">⌄</span></div><div className="preview-sidebar-links"><span>⌕ <span>Search</span></span><span>◷ <span>Activity</span></span><span>✉ <span>Messages</span></span></div><p className="preview-section-label">WORKSPACE</p><div className="preview-project"><BrandMark className="preview-project-icon" /><strong>API Mender</strong></div><div className="preview-selected">▦ <span>Change board</span><em>4</em></div><div className="preview-sidebar-item">≡ <span>Repositories</span></div><div className="preview-sidebar-item">◈ <span>Findings</span></div><div className="preview-sidebar-item">⌁ <span>Sources</span></div><p className="preview-section-label preview-section-label-lower">MONITORING</p><div className="preview-sidebar-item"><span className="source-dot stripe-dot">S</span><span>Stripe</span><span className="preview-online"/></div><div className="preview-sidebar-item"><span className="source-dot github-dot">⌘</span><span>GitHub</span><span className="preview-online"/></div></aside>
    <div className="preview-main"><div className="preview-topline"><div><BrandMark className="preview-project-icon" /><strong>Change board</strong><span className="preview-top-chevron">⌄</span></div><span className="preview-top-avatar">AK</span></div><div className="preview-tabs"><strong>Board view</strong><span>Source activity</span><span>Coverage</span></div><div className="preview-board">{cards.map(column => <section className="preview-column" key={column.column}><div className="preview-column-heading"><span className={`preview-column-pill ${column.tint}`}>{column.column}</span><span>{column.count}</span></div>{column.items.map(item => <article className="preview-card" key={item.title}><div className="preview-card-head"><span className={`preview-provider-icon ${item.provider === 'Stripe' ? 'provider-stripe' : item.provider === 'Payments service' ? 'provider-payments' : 'provider-checkout'}`}>{item.icon}</span><strong>{item.provider}</strong><span className="preview-card-more">···</span></div><div className="preview-card-body"><h3>{item.title}</h3><p>{item.detail}</p><span className={`preview-badge ${item.badgeTone}`}>{item.badge}</span></div><div className="preview-card-foot">◷ <span>{item.foot}</span></div></article>)}</section>)}</div></div>
  </div>;
}
