import { db, getInventory, getPatch, getValidation, listFindings, listRepos, source } from '@/lib/core';

export const dynamic='force-dynamic';
const stamp=(value:string)=>new Date(value).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
export default function Home(){
  if(process.env.DEMO_MODE==='0')return <main className="locked"><div className="mark">R</div><h1>API Mender</h1><p>The live workspace requires sign in.</p><a className="button button-primary" href="/live">Open live workspace</a></main>;
  const findings=listFindings('tenant_demo');const repos=listRepos('tenant_demo') as {id:string;name:string;branch:string;head:string;paused:number;patch_enabled:number}[];
  const f=findings[0],repo=repos[0],inv=repo?getInventory('tenant_demo',repo.id):undefined;
  const v=f?getValidation('tenant_demo',f.id):undefined,p=f?getPatch('tenant_demo',f.id):undefined,s=f?source(f.sourceId):undefined;
  const audits=db().prepare('SELECT actor,action,detail,created_at FROM audit WHERE tenant_id=? ORDER BY id DESC LIMIT 7').all('tenant_demo') as {actor:string;action:string;detail:string;created_at:string}[];
  return <div className="shell">
    <aside className="sidebar"><div className="brand"><div className="brandmark">A<span>↗</span></div><div><strong>API Mender</strong><small>API change monitor</small></div></div><div className="side-label">WORKSPACE</div><nav aria-label="Main navigation"><a className="active" href="#overview"><span>▦</span> Overview</a><a href="#findings"><span>◈</span> Findings <em>{findings.length}</em></a><a href="#integrations"><span>◇</span> Integrations</a><a href="#activity"><span>◷</span> Activity</a><a href="#settings"><span>⚙</span> Settings</a></nav><div className="sidebar-bottom"><div className="avatar">D</div><div><strong>Demo workspace</strong><small>Local fixture</small></div></div></aside>
    <main className="main" id="overview"><div className="topbar"><div className="breadcrumb">Workspace <span>/</span> Overview</div><div className="top-right"><span className="demo-pill">SIMULATED DATA</span><span className="top-avatar">D</span></div></div>
      <div className="content"><header className="page-heading"><div><div className="eyebrow">INTEGRATION OVERVIEW</div><h1>Integration health</h1><p>Upstream changes, mapped to the code that depends on them.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><a className="button button-primary" href="/live">Open live workspace</a><a className="button button-outline" href="/connect"><span>＋</span> GitHub App setup</a></div></header>
      <div className="notice"><span className="notice-icon">!</span><div><strong>Demo environment</strong><p>The Stripe contract change and PR below are simulated. No live Stripe or GitHub activity is shown.</p></div></div>
      <section className="metrics" aria-label="Overview metrics"><div className="metric"><span>MONITORED REPOSITORIES</span><strong>{repos.length.toString().padStart(2,'0')}</strong><small>{repos.length?'1 integration discovered':'No repositories yet'}</small></div><div className="metric"><span>OPEN FINDINGS</span><strong>{findings.filter(x=>!['Resolved','Dismissed','Superseded'].includes(x.status)).length.toString().padStart(2,'0')}</strong><small>Requires engineering review</small></div><div className="metric"><span>PATCHES VALIDATED</span><strong>{v?.status==='passed'?'01':'00'}</strong><small>{v?.status==='passed'?'All fixture checks passed':'No passing validation'}</small></div><div className="metric"><span>MONITORING COVERAGE</span><strong className="coverage">Partial</strong><small>API version unresolved</small></div></section>
      <div className="grid"><section className="panel findings-panel" id="findings"><div className="panel-head"><div><div className="eyebrow">TRIAGE QUEUE</div><h2>Findings</h2></div><span className="count">{findings.length} total</span></div>{f?<><div className="finding-row"><div className="finding-symbol">↗</div><div className="finding-body"><div className="finding-top"><span className="severity">HIGH</span><span className="confidence">CONFIRMED IN FIXTURE</span></div><h3>{f.title}</h3><p>{f.description}</p><div className="finding-meta"><span>Stripe</span><span>·</span><span>{repo?.name}</span><span>·</span><span>{stamp(f.createdAt)}</span></div></div><span className="status">{f.status==='PR opened'?'Local PR artifact':f.status}</span></div><div className="finding-detail"><div className="detail-title">What changed</div><p>A simulated contract adds <code>capture_method</code> to the required request fields for <code>POST /v1/payment_intents</code>. The sample call omits it.</p><div className="detail-columns"><div><span className="detail-label">AFFECTED CALL SITE</span><strong>{f.affected[0]?.file}:{f.affected[0]?.line}</strong><small>{f.affected[0]?.symbol}</small></div><div><span className="detail-label">POTENTIAL FAILURE</span><strong>Request rejection</strong><small>{f.failureMode}</small></div></div><div className="evidence"><span>◫</span><div><strong>Evidence trace</strong><p>{f.evidence}</p><small>SHA-256 {s?.hash.slice(0,24)}… · captured {s?stamp(s.retrievedAt):'—'}</small></div></div><div className="caution">Coverage gap: {f.limitations.join('; ')}. Live applicability has not been verified.</div></div></>:<div className="empty">Run <code>npm run demo</code> to load the reproducible fixture.</div>}</section>
      <div className="right-stack"><section className="panel" id="integrations"><div className="panel-head"><div><div className="eyebrow">CONNECTED SOURCE</div><h2>Integration inventory</h2></div><span className="stripe-icon">S</span></div>{repo?<><div className="repo-line"><div><strong>{repo.name}</strong><small>Branch: {repo.branch}</small></div><span className="status status-blue">{repo.paused?'Paused':'Monitoring'}</span></div><div className="inventory-grid"><div><span>PROVIDER</span><strong>Stripe</strong></div><div><span>SDK VERSION</span><strong>{inv?.sdkVersion||'Unknown'}</strong></div><div><span>API VERSION</span><strong className="warn">{inv?.apiVersion||'Unresolved'}</strong></div><div><span>CALL SITES</span><strong>{inv?.calls.length||0}</strong></div></div><p className="small-note">Static analysis covers recognized TypeScript calls. Dynamic requests and changes outside the tracked sources may be missed.</p></>:<p className="empty">No repository connected.</p>}</section><section className="panel validation-panel"><div className="panel-head"><div><div className="eyebrow">PATCH REVIEW</div><h2>Validation</h2></div><span className={v?.status==='passed'?'passed':'pending'}>{v?.status==='passed'?'Passed':'Pending'}</span></div>{v?<><div className="checks">{v.checks.map(c=><div key={c.name}><span className={c.ok?'check-ok':'check-bad'}>{c.ok?'✓':'×'}</span><span>{c.name}</span><strong>{c.ok?'Passed':'Failed'}</strong></div>)}</div><a className="artifact-link" href="/api/demo/artifact?type=pr">View local PR summary <span>↗</span></a><a className="artifact-link second" href="/api/demo/artifact?type=patch">View patch diff <span>↗</span></a></>:<p className="empty">No validation run yet.</p>}</section></div></div>
      <div className="bottom-grid"><section className="panel" id="activity"><div className="panel-head"><div><div className="eyebrow">TRACEABILITY</div><h2>Recent activity</h2></div></div><div className="activity">{audits.map((a,i)=><div key={i}><span className="activity-dot"/><div><strong>{a.action.replaceAll('.',' · ')}</strong><small>{a.actor} · {stamp(a.created_at)}</small></div></div>)}</div></section><section className="panel settings" id="settings"><div className="panel-head"><div><div className="eyebrow">WORKSPACE</div><h2>Monitoring controls</h2></div></div><div className="setting-row"><div><strong>Repository monitoring</strong><small>Scheduled source checks for {repo?.name||'selected repository'}</small></div><span>{repo?.paused?'Paused':'On'}</span></div><div className="setting-row"><div><strong>Patch generation</strong><small>Requires a reviewed finding and validation</small></div><span>{repo?.patch_enabled?'On':'Off'}</span></div><p className="small-note">Control changes require a tenant token through the API. The fixture dashboard is read only.</p></section></div>
      <footer>API Mender demo · Contract evidence is simulated · Human approval required before merge</footer></div></main></div>;
}
