'use client';

import { useState } from 'react';
import ProductPreview from './product-preview';

type Props = { ready: boolean; email: string; password: string; message: string; busy: boolean; awaitingConfirmation: boolean; onEmailChange: (value: string) => void; onPasswordChange: (value: string) => void; onAuthenticate: (mode: 'signin' | 'signup') => Promise<void>; onResend: () => Promise<void>; onBack: () => void };

export default function AuthScreen({ ready, email, password, message, busy, awaitingConfirmation, onEmailChange, onPasswordChange, onAuthenticate, onResend, onBack }: Props) {
  const [mode, setMode] = useState<'signin' | 'signup'>('signup');
  const [showEmail, setShowEmail] = useState(false);
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); void onAuthenticate(mode); };
  return <main className="auth-layout"><section className="auth-left"><a className="auth-home-link" href="/" aria-label="Back to API Mender home">← Back to home</a><div className="auth-panel"><a className="site-brand auth-brand" href="/"><span className="site-brand-icon">↗</span><span>api mender<span className="brand-period">.</span></span></a>
    {!ready ? <p className="auth-loading">Loading workspace…</p> : awaitingConfirmation ? <div className="auth-confirmation"><h1>You&apos;ve got mail<span className="brand-period">.</span></h1><p>A confirmation email was requested for <strong>{email}</strong>. Check your inbox and spam folder, then follow the link to confirm your account.</p><button className="pill-button pill-outline auth-submit" disabled={busy} onClick={() => void onResend()}>Resend email</button><button className="auth-text-button" onClick={onBack}>Back to sign in</button>{message && <p className="auth-message" role="status">{message}</p>}</div> : <div className="auth-entry"><h1>Stay ahead of<br/>every API change<span className="brand-period">.</span></h1><p className="auth-intro">Your integrations, their upstream changes, and the code they touch—all in one place.</p><div className="auth-mode-tabs" role="tablist" aria-label="Account access"><button type="button" role="tab" aria-selected={mode === 'signup'} className={mode === 'signup' ? 'selected' : ''} onClick={() => setMode('signup')}>Create account</button><button type="button" role="tab" aria-selected={mode === 'signin'} className={mode === 'signin' ? 'selected' : ''} onClick={() => setMode('signin')}>Sign in</button></div>{!showEmail && <button className="pill-button pill-dark auth-email-first" onClick={() => setShowEmail(true)}>Continue with email <span aria-hidden="true">↗</span></button>}{showEmail && <form onSubmit={submit} className="auth-form"><label htmlFor="auth-email">Email</label><input id="auth-email" type="email" autoComplete="email" placeholder="name@work-email.com" value={email} onChange={event => onEmailChange(event.target.value)} required/><label htmlFor="auth-password">Password</label><input id="auth-password" type="password" autoComplete={mode === 'signup' ? 'new-password' : 'current-password'} placeholder={mode === 'signup' ? 'Create a password' : 'Your password'} value={password} onChange={event => onPasswordChange(event.target.value)} required minLength={6}/><button className="pill-button pill-dark auth-submit" disabled={busy || !email || !password} type="submit">{busy ? 'Please wait…' : mode === 'signup' ? 'Create account' : 'Sign in'} <span aria-hidden="true">↗</span></button></form>}{email && <button className="auth-text-button" disabled={busy} onClick={() => void onResend()}>Resend confirmation email</button>}{message && <p className="auth-message" role="status">{message}</p>}<p className="auth-footnote">By continuing, you agree to use API Mender for your own authorized repositories.</p></div>}
  </div><div className="auth-left-footer"><span>API Mender</span><a href="/demo">Explore demo ↗</a></div></section><aside className="auth-right"><div className="auth-preview-wrap"><ProductPreview /></div><div className="auth-right-caption"><span className="caption-spark">✦</span><div><strong>Changes in context.</strong><span>From the source to your code, without the guesswork.</span></div></div></aside></main>;
}
